# Please set dir for temp header files
HEADERS_DIR=../include

INCLUDE=-I. -I../common -I../module -I../file -I../parse -I../utopia -I$(HEADERS_DIR) -I../prime -I../chars
CFLAGS=-Wall -g -D_DEBUG ${INCLUDE}
